language: java
jdk:
    - oraclejdk11
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'
script:
    - gradle check
    - gradle build

before_install:
    - chmod +x gradlew