language: java

jdk:
    - openjdk11

before_install:
    - chmod +x mvnw

branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

script: "./gradlew clean build"