# Common configuration
spring:
    profiles:
        active: prod
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
        open-in-view: false
    datasource: # DB 설정
        driver-class-name: com.mysql.cj.jdbc.Driver
        tomcat:
            max-active: 50
            max-idle: 20
            min-idle: 15
        hikari:
            auto-commit: false
            maximum-pool-size: 20
        sql-script-encoding: UTF-8
    resources:
        static-locations: classpath:/static/
    servlet:
        multipart:
            enabled: true
            max-file-size: 1MB
            max-request-size: 10MB
server:
    address: 127.0.0.1
    servlet:
        session:
            timeout: 1440m
    error:
        path: /error

#    servlet:
#        context-path: /api

logging:
    file: web.log
    level:
        root: info
        org:
            hibernate:
                SQL: info
                type.descriptor.sql.BasicBinder: info

app:
    video-server:
        address: https://127.0.0.1:86/api/
        api-key: VBLWA8_tJEGnZNGy
    admin-info:
        name: Administrator
        email: devplayg@devplayg.com
    use-ip-blocking: false
    file-upload-dir: /upload
    home-uri: /audit/
    name: Spring Boot 201
    path-patterns-not-to-be-intercepted:
        - /public/**
        - /login/**
        - /favicon.ico
        - /assets/**
        - /modules/**
        - /plugins/**
        - /css/**
        - /font/**
        - /img/**
        - /js/**
---
#
# Development mode
#
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: Uniiot12!@
        tomcat:
            max-active: 3
            max-idle: 3
            min-idle: 3
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false

server:
    port: 80

logging:
    level:
        com.devplayg: debug

---
#
# Production mode
#
spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: Uniiot12!@
server:
    port: 443
    ssl:
        enabled: true
        key-store: certificate/sb201.key
        key-store-password: devplayg
        key-password: devplayg
        key-alias: sb201
        trust-store: certificate/sb201.ts
        trust-store-password: devplayg
        enabled-protocols:
            - TLSv1.2
            - TLSv1.3