# Common configuration
spring:
    profiles:
        active: dev
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
        open-in-view: false
    datasource: # DB 설정
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            auto-commit: false
        sql-script-encoding: UTF-8
    resources:
        static-locations: classpath:/static/
#    jackson:
#        date-format: yyyy/MM/dd HH:mm:ss
#        time-zone: America/Sao_Paulo
server:
    address: 127.0.0.1
    servlet:
        session:
            timeout: 1440m
    error:
        path: /error

#    servlet:
#        context-path: /api

logging:
    level:
        root: info
        com.devplayg: debug
        org:
            mybatis: info
            hibernate:
                SQL: info
                type.descriptor.sql.BasicBinder: info

app:
    adminInfo:
        name: Administrator
        email: admin@admin.com
    home-uri: /audit/
    name: Spring Boot 201
    path-patterns-not-to-be-intercepted:
        - /test/**
        - /login/**
        - /favicon.ico
        - /assets/**
        - /modules/**
        - /plugins/**
        - /css/**
        - /font/**
        - /img/**
        - /js/**
---
#
# Development mode
#
spring:
    profiles: dev
    devtools:
        livereload:
            enabled: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: Uniiot12!@
        tomcat:
            max-active: 3
            max-idle: 3
            min-idle: 3
    thymeleaf:
        cache: false
server:
    port: 80
logging:
    file: logs/web-dev.log

---
#
# Production mode
#
spring:
    profiles: prod
    devtools:
        livereload:
            enabled: false
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: Uniiot12!@
        tomcat:
            max-active: 50
            max-idle: 20
            min-idle: 1
server:
    port: 8080
logging:
    file: logs/web-dev.log