# Common configuration
spring:
    profiles:
        active: dev
    messages:
        basename: i18n/messages

server:
    address: 127.0.0.1
    error:
        path: /error

logging:
    level:
        root: info
        com.devplayg: info
        org:
            mybatis: info
            hibernate:
                SQL: info
                type.descriptor.sql.BasicBinder: info


---
# Development mode
spring:
    profiles: dev
server:
    port: 80
logging:
    file: logs/web-dev.log

---
# Production mode
spring:
    profiles: prod
server:
    port: 8080
logging:
    file: logs/web-dev.log